# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Data 100
description: Principles and Techniques of Data Science
author: Joseph E. Gonzalez, Narges Norouzi
baseurl: '/sp24' # the subpath of your site, e.g. /blog
url: 'https://ds100.org' # the base hostname & protocol for your site, e.g. http://example.com
logo: 'resources/assets/favicon/panda-logo.png'

# Theme settings
remote_theme: just-the-docs/just-the-docs@v0.5.2
color_scheme: light
search_enabled: true
permalink: pretty


# External navigation links
nav_external_links:
  - title: Course Notes
    url: https://ds100.org/course-notes/
    hide_icon: true
    # opens_in_new_tab: true
  - title: Debugging Guide
    url: https://ds100.org/debugging-guide/
    hide_icon: true
    # opens_in_new_tab: true
  - title: Course FAQ
    url: https://ds100.org/faqs/sp24/
    hide_icon: true
    # opens_in_new_tab: true

footer: >-
  Powered by <a href="https://github.com/kevinlin1/just-the-class">Just the Class</a>
heading_anchors: false

color_scheme: wider

# Collections for website data
collections:
  - modules
  - announcements
  - staffers
# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: modules
    values:
      layout: module
  - scope:
      path: ''
      type: announcements
    values:
      layout: announcement
  - scope:
      path: ''
      type: staffers
    values:
      layout: staffer

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red